# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:               Syntonic
tagline:             'Developer Blog'
description:         'Syntonic Developer Blog'
url:                 https://blog.syntonic.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Syntonic
  url:               https://syntonic.io
  email:             ideas@syntonic.io

# Custom vars
version:             1.0.0
